=== zateyev/Transporter/src/main/resources/trucks.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.epam.com/trucks"
           xmlns:tns="http://www.epam.com/trucks"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
    <xs:element name="trucks" type="tns:Trucks"/>

    <xs:complexType name="Trucks">
        <xs:sequence>
            <xs:element name="truck" type="tns:Truck" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Truck">
        <xs:all>
            <xs:element name="uuid" type="tns:UUID"/>
            <xs:element name="model" type="xs:string"/>
            <xs:element name="capacityByWeight" type="xs:positiveInteger"/>
            <xs:element name="capacityByVolume" type="xs:positiveInteger"/>
            <xs:element name="pricePerKm" type="xs:positiveInteger"/>
            <xs:element name="manufactureDate" type="xs:date"/>
        </xs:all>
    </xs:complexType>
    <xs:simpleType name="UUID">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== zateyev/Transporter/src/main/resources/trucks.xml
<?xml version="1.0" encoding="UTF-8"?>
<trucks xmlns="http://www.epam.com/trucks"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.epam.com/trucks http://www.epam.com/trucks/trucks.xsd">
    <truck>
        <uuid>12345678-1234-1234-1234-123412341231</uuid>
        <model>Газель</model>
        <capacityByWeight>1500</capacityByWeight>
        <capacityByVolume>9</capacityByVolume>
        <pricePerKm>30</pricePerKm>
        <manufactureDate>2001-10-03</manufactureDate>
    </truck>
    <truck>
        <uuid>12345678-1234-1234-1234-123412341232</uuid>
        <model>Scania</model>
        <capacityByWeight>8000</capacityByWeight>
        <capacityByVolume>56</capacityByVolume>
        <pricePerKm>70</pricePerKm>
        <manufactureDate>2001-10-03</manufactureDate>
    </truck>
    <truck>
        <uuid>12345678-1234-1234-1234-123412341233</uuid>
        <model>Foton</model>
        <capacityByWeight>3000</capacityByWeight>
        <capacityByVolume>20</capacityByVolume>
        <pricePerKm>50</pricePerKm>
        <manufactureDate>2001-10-03</manufactureDate>
    </truck>
    <truck>
        <uuid>12345678-1234-1234-1234-123412341234</uuid>
        <model>Газель</model>
        <capacityByWeight>1500</capacityByWeight>
        <capacityByVolume>9</capacityByVolume>
        <pricePerKm>30</pricePerKm>
        <manufactureDate>2001-10-03</manufactureDate>
    </truck>
    <truck>
        <uuid>12345678-1234-1234-1234-123412341235</uuid>
        <model>Daf</model>
        <capacityByWeight>20000</capacityByWeight>
        <capacityByVolume>100</capacityByVolume>
        <pricePerKm>100</pricePerKm>
        <manufactureDate>2001-10-03</manufactureDate>
    </truck>
</trucks>
